### ISSUE TITLE
admin routes modules are not properly generated with the entity generator

### ISSUE THREAD

**Issue by olimolly** [CeddyG/Clara#6]
Modules routes are not properly generated for back-office modules files when using the entity generator.

The command artisan publish modules works fine but copy admin files into: 
views/vendor/[module]/admin

Admin files should be split into views/admin/[module]

FR
Les routes admin des modules (page builder, news, event etc) ne sont pas bien générés avec l'entity generator. Lorsque l'on va sur le back-office, ce sont les vues dans CeddyG/ qui sont appelées.
La commande artisan vendor publish [module] fonctionne bien et adapte bien les routes aux nouvelles vues admin mais uniquement dans le dossier. views/vendor/[modules]/admin.
Il faut réecrire la route à la main si l'on veut déplacer les vues admin d'un module dans le dossier views/admin/[modules].

**Comment by CeddyG** [comment]
Salut @OlivierMorelle ,

Tu voudrais que lorsque l'on génère une vue d'un module elle aille automatiquement dans views/vendor/[modules]/admin plutôt que dans views/admin/[module] ? Il faudrait que le système détecte les tables qui appartiennent à un module ou pas pour savoir où ranger les vues.

Un moyen simple en attendant, c'est de mettre que cette ligne là : @include('views/admin/[module]') dans la vue qui se trouve dans views/vendor/[modules]/admin.

**Comment by olimolly** [comment]
Non justement l'inverse mais c'est peut-être ce que tu voulais dire. Parce que, en effet l'include permet de faire ça mais le but et d'avoir "une belle" arborescence.

Pour récapituler...
Par défaut, les modules sont générés dans le vendor, ça fonctionne bien mais c'est pas terrible pour l'arborescence.
Si on veut garder une "belle" arbo et déplacer les vues admin, il faut bidouiller pour adapter les routes, 

![arbo-admin-clara](https://user-images.githubusercontent.com/32452264/71265049-b1261500-2345-11ea-9f29-9a4e0300b0d9.jpg)


PS: Sinon j'ai fait des migrations avec les tables de bases si ça t'intéresse.
